export const layoutPermissionType = {
    LOAD_PERMISSION_DATA_START:"LOAD_PERMISSION_DATA_START",
    SET_PERMISSION_SUCCESS: "SET_PERMISSION_SUCCESS",
    SET_PERMISSION_ERROR: "SET_PERMISSION_ERROR"

}
